version: 1.3.1.{build}

# Build on Windows and macOS (FREE for open source!)
# Note: Linux builds disabled due to AppImage network issues in AppVeyor
image:
  - Visual Studio 2022      # Windows
  - macos-monterey          # macOS

# Environment
environment:
  PYTHON: "C:\\Python312"
  PYTHON_VERSION: "3.12"
  PYTHON_ARCH: "64"

# Only build on specific branches
branches:
  only:
    - main
    - feature/ui-rewrite

# Don't build on tag pushes
skip_tags: false

# Install dependencies
install:
  # Windows
  - cmd: SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  - cmd: python --version
  - cmd: python -m pip install --upgrade pip
  - cmd: pip install briefcase

  # macOS
  - sh: |
      if [[ "$APPVEYOR_BUILD_WORKER_IMAGE" == macos* ]]; then
        python3 --version
        pip3 install --upgrade pip
        pip3 install briefcase
      fi

# Build steps
build_script:
  # Windows
  - cmd: echo Building for Windows...
  - cmd: briefcase create windows
  - cmd: briefcase build windows
  - cmd: briefcase package windows --adhoc-sign

  # macOS
  - sh: |
      if [[ "$APPVEYOR_BUILD_WORKER_IMAGE" == macos* ]]; then
        echo "Building for macOS..."
        briefcase create macOS
        briefcase build macOS
        briefcase package macOS --adhoc-sign
      fi

# Test step (optional)
test_script:
  - cmd: echo "Windows build complete"
  - sh: echo "Unix build complete"

# Collect artifacts
artifacts:
  # Windows MSI
  - path: 'dist\*.msi'
    name: WindowsInstaller
    type: File

  # macOS DMG
  - path: 'dist/*.dmg'
    name: macOSDMG
    type: File

# Deployment (optional - for releases)
# deploy:
#   - provider: GitHub
#     auth_token:
#       secure: YOUR_ENCRYPTED_GITHUB_TOKEN
#     artifact: /.*\.(dmg|msi|AppImage)/
#     on:
#       branch: main
#       appveyor_repo_tag: true

# Notifications
notifications:
  - provider: Email
    to:
      - nerveband@gmail.com
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true
