name: Build Windows App

on:
  push:
    branches: [ main, feature/ui-rewrite ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allow manual trigger

jobs:
  build-windows-x86_64:
    name: Build Windows x86_64 MSI Installer
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          architecture: 'x64'  # Explicitly use x86_64

      - name: Install Briefcase
        run: |
          python -m pip install --upgrade pip
          pip install briefcase

      - name: Clean previous builds
        run: |
          if (Test-Path build) { Remove-Item -Recurse -Force build }
          if (Test-Path dist) { Remove-Item -Recurse -Force dist }

      - name: Create Windows app (force fresh template)
        run: briefcase create windows app --update-resources

      - name: Build Windows app
        run: briefcase build windows app

      - name: Package Windows MSI installer
        run: briefcase package windows app

      - name: Upload Windows MSI artifact
        uses: actions/upload-artifact@v4
        with:
          name: apple-music-history-converter-windows-x86_64-msi
          path: dist/*.msi
          if-no-files-found: error
          retention-days: 90
