name: Build Application

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        include:
          - os: macos-latest
            output_name: "Apple Music History Converter-macOS"
          - os: windows-latest
            output_name: "Apple Music History Converter-Windows"

    steps:
    # Initial Setup
    - uses: actions/checkout@v4
      with:
        clean: true

    # Build Environment Setup
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    # Dependencies
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    # Build for macOS
    - name: Build with PyInstaller (macOS)
      if: runner.os == 'macOS'
      shell: bash
      run: |
        # Use the build script from build_artifacts
        cd build_artifacts
        chmod +x build_macos.sh
        ./build_macos.sh

    # Build for Windows
    - name: Build with PyInstaller (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        # Use the build script from build_artifacts
        cd build_artifacts
        .\build_windows.bat

    # Artifact Upload
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.os }}-build
        path: |
          build_artifacts/*.zip
          build_artifacts/*.exe
          build_artifacts/*.tar.gz
        if-no-files-found: error

  # Release Creation
  create-release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true

      # Create new release
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/*
          draft: false
          prerelease: false
          body: |
            **Apple Music History Converter v2.0.1**
            
            ### Downloads and Installation
            
            **macOS (Apple Silicon/Intel)**
            - Download `Apple Music History Converter-macOS.zip`
            - Extract the zip file
            - Right-click the app and select "Open" (required for unsigned apps)
            - If you get a security warning, go to System Settings > Privacy & Security and click "Open Anyway"
            
            **Windows (x64)**
            - Download `Apple Music History Converter-Windows.exe`
            - Run the executable
            - If you get a SmartScreen warning, click "More info" and "Run anyway"
            
            **Linux Users**
            To compile from source:
            ```bash
            # Clone the repository
            git clone https://github.com/nerveband/Apple-Music-Play-History-Converter.git
            cd Apple-Music-Play-History-Converter
            
            # Create a virtual environment (recommended)
            python -m venv venv
            source venv/bin/activate  # On Linux/macOS
            
            # Install dependencies
            pip install pandas requests
            
            # Run the script
            python apple_music_play_history_converter.py
            ```
            
            ### Usage Instructions
            1. Export your Apple Music Library:
               - Open Apple Music
               - Go to File > Library > Export Library
               - Save the XML file somewhere convenient
            
            2. Run the converter:
               - Launch the application
               - Click "Select File" to choose your exported XML file
               - Choose your desired output format
               - Select where to save the converted file
               - Click "Convert" to process your library
            
            ### Notes
            - The macOS version is unsigned - follow the instructions above to open it
            - Windows Defender or SmartScreen may show a warning - this is normal for unsigned applications
            - For any issues, please create a ticket in the Issues section
            
            ### Requirements
            - macOS 10.15 or later
            - Windows 10 or later
            - For Linux: Python 3.8 or later with pandas and requests packages